### ISSUE TITLE
fps knob

### ISSUE THREAD

**Issue by LarsCawley** [jeangjenq/ffmpeg_write#1]
It would be great if the fps knob was a float rather than int.  23.976 is a commonly used framerate.

**Comment by jeangjenq** [comment]
Good point. Updated fps to a float knob. 
However I found if your project settings is set to 23.976, the node still set itself to 23 on create. You need to manually change it after creating. This is due to `nuke.root().fps()` seems to be returning int only.

**Comment by LarsCawley** [comment]
Thanks, Jean.  I can't find the place where your callback sets the fps knob on your node, based on the scene root.  nuke.root()['fps'] is a float knob and should return a float value.

**Comment by jeangjenq** [comment]
@LarsCawley You're right `nuke.root()['fps'].value()` returned float, while `nuke.root().fps()` always returned int. I'll update it when I get home but if you want you can find the onCreate in [ffmpeg_write.nk](https://github.com/jeangjenq/ffmpeg_write/blob/master/ffmpeg_write.nk)
